### ISSUE TITLE
下載卡在0%

### ISSUE THREAD

**Issue by clalanliu** [jameshwc/Ceiba-Downloader#1]
下載會卡在0%，沒辦法像圖示那樣順利下載QQ

**Comment by jameshwc** [comment]
請問你是用 python 直接執行的嗎？如果是，終端機有沒有輸出什麼 error 呢？
可以讓我看一下有問題的截圖嗎？
如果是載 Release 頁面的 exe，有可能是因為 Python 版本我沒弄好的關係，我有上傳最新版本的程式碼和程式，你可以用看看

**Comment by jameshwc** [comment]
這陣子密切的更新應該解決了這個問題。
