### ISSUE TITLE
"修課學生" 名單 is wrong.  

### ISSUE THREAD

**Issue by LiChungYi** [jameshwc/Ceiba-Downloader#11]
This is a nice tool. It works well for me on Windows with the release binary.

I see some minor bugs like "修課學生" 名單 is wrong. When there are many students, only the first page of the list is saved. Maybe it is better to click "顯示全部" before saving. Or maybe this is hard to fix.

**Comment by jameshwc** [comment]
Hi thank you for using this tool!

The default page of '修課學生' shows only a limited amount of students; however, the '顯示全部' page is downloaded too, so that you can click '顯示全部' to show all the students.

Maybe it can download the '顯示全部' page as the default page in the next version, but it adds up some coding complexity. I'll think about it. Thanks for the suggestion.

**Comment by LiChungYi** [comment]
No need to change the order. 

The problem I saw was that the '顯示全部' page was not downloaded correctly.
I checked a bit more and I found that this problem did not occur all the time. It only happened for some of my courses.

Anyway, this is a minor issue. I just want to leave a record and we can revisit if someone else has the same issue.

**Comment by jameshwc** [comment]
I found out where this error came from.

Ceiba doesn't specify course code in some URLs. For example, the URLs of '顯示全部' in the student module of all courses are the same: 'https://ceiba.ntu.edu.tw/modules/student/student.php?current_lang=chinese&all=1&sort='.

I use a cache technic to skip downloading repetitive URLs. Therefore, a URL like this will be skipped and the hyperlink will link to the counterpart of another course that's been downloaded before.

I'll fix it in the next version, thank you for pointing out the issue.

**Comment by LiChungYi** [comment]
The fix causes another error:

2022-01-19 20:42:55 - ERROR - 'WindowsPath' object has no attribute 'is_relative_to'

**Comment by jameshwc** [comment]
> The fix causes another error:
> 
> 2022-01-19 20:42:55 - ERROR - 'WindowsPath' object has no attribute 'is_relative_to'

My fault. I used a feature that's only available in python 3.9+. I've fixed it. Thanks.

**Comment by LiChungYi** [comment]
Thanks. I confirmed that this is fixed now.
