### ISSUE TITLE
The program is stuck when there is a broken external image.

### ISSUE THREAD

**Issue by LiChungYi** [jameshwc/Ceiba-Downloader#12]
In one of my courses, people posted external images in the forum. 
One of the external images is broken now.
The downloader should have skipped downloading the image, but it does not. 
It keeps retrying and the program is stuck.

**Comment by jameshwc** [comment]
Thanks for letting me know the issue.
I'll fix it when I have time.

**Comment by LiChungYi** [comment]
Sure, take your time.

Error message was like:

2022-01-17 19:44:05 - INFO - 五秒後重新連線...
2022-01-17 19:29:15 - ERROR - HTTPConnectionPool(host='pic.eslite.com', port=80): Max retries exceeded with url: /Upload/Product/200806/m/633519138269950996.jpg (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

You probably should update the loop_connect() to break the loop after it fails many times, and the caller needs to deal with such error.

**Comment by jameshwc** [comment]
Can you please upload the HTML code/file of the page that causes this specific error? That will save me a lot of work and prevent any potential errors.

**Comment by LiChungYi** [comment]
[The file has been deleted by @jameshwc]
After you have the fix, lets delete this file if possible to avoid copy right issues.

**Comment by jameshwc** [comment]
Hi Chung Yi, I've fixed #11 and #12 in PR #13. It'd be great if you can test whether the program runs correctly before I merge it. You can test it with the [pre-release](https://github.com/jameshwc/Ceiba-Downloader/releases/tag/latest).
I'll merge it anyway tomorrow night. Many thanks again!

**Comment by LiChungYi** [comment]
I confirmed that this bug has been fixed too.
