### ISSUE TITLE
網頁版本（Web Version）？

### ISSUE THREAD

**Issue by jameshwc** [jameshwc/Ceiba-Downloader#2]
視窗程式的開發差不多告一段落了，有人問做成網頁會不會比較方便，所以想在這做個調查，如果有個網頁可以讓你輸入認證資訊（帳密或 Cookies）和想下載的課程，就能打包成壓縮檔讓你下載，你會比較想使用網頁而不是視窗程式嗎？

如果會的話請幫我按讚投票，不會也可以投倒讚讓我知道一下，謝謝！

**Comment by WildfootW** [comment]
聽起來好恐懼
