### ISSUE TITLE
關鍵字勾選

### ISSUE THREAD

**Issue by brianw0924** [jameshwc/Ceiba-Downloader#30]
有沒有用關鍵字 取消 or 勾選 特定課程的下載項目
e.g. 我要取消下載所有課名含有"國防"的資料

**Comment by jameshwc** [comment]
除了國防、服學可能會有這類需求以外，還有其他的使用情境嗎？
這個功能實作不難，但由於介面的空間有限，如果不是很必要的功能，我會希望能盡量維持介面的簡潔、不雜亂，而犧牲部分使用者的方便
或是你有什麼好的介面設計可以提出來我們討論看看？

**Comment by jameshwc** [comment]
不必要的功能
