### ISSUE TITLE
[firefox] button.html fail redirecting to proper link

### ISSUE THREAD

**Issue by jerejesse** [jameshwc/Ceiba-Downloader#39]
下載完的資料夾，點入課程後左邊的按鈕欄位無法開啟原本所要開啟的連結。
使用上我預期點下課程內容要打開syllabus/syllabus.html，但那個按鍵的連結是button.html。

我另外測試後，**chrome可以正常打開對應連結**，**firefox則沒有反應**，但firefox使用原本ceiba網站是可以正常打開的。

**Comment by jameshwc** [comment]
你好，因為 Firefox 預設設定禁止 Local files 以 Ajax 的方式存取其他資料夾的檔案。解法：在設定（about:config）裡將`security.fileuri.strict_origin_policy` 設為 `false` 即可解決。

![image](https://user-images.githubusercontent.com/45334777/174494669-3a4e8f8f-c16d-435e-b4e9-cb26551fe71e.png)

source: 
> security.fileuri.strict_origin_policy helps when one needs to get the content of one local file through AJAX into another and the first one is not in the same folder (or in subfolder of that folder) as the second one. – [YakovL](https://stackoverflow.com/users/3995261/yakovl)

Ref: [Disable cross domain web security in Firefox](https://stackoverflow.com/questions/17711924/disable-cross-domain-web-security-in-firefox)

**Comment by jerejesse** [comment]
依照解法成功解決，謝謝。
